// This file is auto-generated by the prebuild script. Do not edit manually.

import { ImageData } from '../types';

export const tagsGenerated: string[] = [];

export const imagesGenerated: ImageData[] = [];